In [17]:
# !git clone https://github.com/PhonePe/pulse.git

In [1]:
import os
import json
import pandas as pd
from sqlalchemy import create_engine

In [41]:
csv_filepath = "csv/"

In [2]:

# create SQLite database connection
engine = create_engine("sqlite:///phonepay.db")

### 1. Aggregated

#### 1.1 Aggregated - Insurance

In [39]:
# 
# pulse\data\aggregated\insurance\country\india\state

# Path to dataset
path = "pulse/data/aggregated/insurance/country/india/state/"

data = []

# Loop through states
for state in os.listdir(path):
    state_path = path + state + "/"
    
    for year in os.listdir(state_path):
        year_path = state_path + year + "/"
        
        for file in os.listdir(year_path):
            file_path = year_path + file
            
            with open(file_path, 'r') as f:
                d = json.load(f)
                
                for i in d['data']['transactionData']:
                    name = i['name']
                    
                    for j in i['paymentInstruments']:
                        data.append({
                            "state": state,
                            "year": int(year),
                            "quarter": int(file.strip('.json')),
                            "transaction_type": name,
                            "count": j['count'],
                            "amount": j['amount']
                        })

df = pd.DataFrame(data)

df.to_csv("csv/aggreated_insurance.csv",index=False)

# Inserting Data into sql

table_name = 'aggreated_insurance'
df.to_sql(name=table_name, con=engine, if_exists='replace', index=False)

print(f"Data inserted successfully to {table_name} table")
df.head()

Data inserted successfully to aggreated_insurance table

                       state  year  quarter transaction_type  count    amount
0  andaman-&-nicobar-islands  2020        2        Insurance      6    1360.0
1  andaman-&-nicobar-islands  2020        3        Insurance     41   15380.0
2  andaman-&-nicobar-islands  2020        4        Insurance    124  157975.0
3  andaman-&-nicobar-islands  2021        1        Insurance    225  244266.0
4  andaman-&-nicobar-islands  2021        2        Insurance    137  181504.0

#### 1.2 Aggregated-transaction

In [42]:

# Path to dataset
path = "pulse/data/aggregated/transaction/country/india/state/"

data = []

# Loop through states
for state in os.listdir(path):
    state_path = path + state + "/"
    
    for year in os.listdir(state_path):
        year_path = state_path + year + "/"
        
        for file in os.listdir(year_path):
            file_path = year_path + file
            
            with open(file_path, 'r') as f:
                d = json.load(f)
                
                for i in d['data']['transactionData']:
                    name = i['name']
                    
                    for j in i['paymentInstruments']:
                        data.append({
                            "state": state,
                            "year": int(year),
                            "quarter": int(file.strip('.json')),
                            "transaction_type": name,
                            "count": j['count'],
                            "amount": j['amount']
                        })

df = pd.DataFrame(data)

# Storing data to csv file for future purpose
df.to_csv(csv_filepath+"aggreated_transactions.csv",index=False)

# Inserting Data into sql for analysing
table_name = 'aggreated_transaction'
df.to_sql(name=table_name, con=engine, if_exists='replace', index=False)

print(f"Data inserted successfully to {table_name} table")
df.head()

Data inserted successfully to aggreated_transaction table

,state,year,quarter,transaction_type,count,amount
0,andaman-&-nicobar-islands,2018,1,Recharge & bill payments,4200,1.845307e+06
1,andaman-&-nicobar-islands,2018,1,Peer-to-peer payments,1871,1.213866e+07
2,andaman-&-nicobar-islands,2018,1,Merchant payments,298,4.525072e+05
3,andaman-&-nicobar-islands,2018,1,Financial Services,33,1.060142e+04
4,andaman-&-nicobar-islands,2018,1,Others,256,1.846899e+05

#### 1.3 Aggregated - user

In [43]:

# Path to dataset
path = "pulse/data/aggregated/user/country/india/state/"

data = []

# Loop through states
for state in os.listdir(path):
    state_path = path + state + "/"
    
    for year in os.listdir(state_path):
        year_path = state_path + year + "/"
        
        for file in os.listdir(year_path):
            file_path = year_path + file
            
            with open(file_path, 'r') as f:
                d = json.load(f)
                if d['data']['usersByDevice']:
                    for i in d['data']['usersByDevice']:
                        # {"brand":"Vivo","count":15056,"percentage":0.2424671873741847}
                        data.append({
                            "state": state,
                            "year": int(year),
                            "quarter": int(file.strip('.json')),
                            "brand": i['brand'],
                            "count": i['count'],
                            "amount": i['percentage']
                        })

df = pd.DataFrame(data)

df.to_csv(csv_filepath+"aggreated_user.csv",index=False)

# Inserting Data into sql for analysing
table_name = 'aggreated_user'
df.to_sql(name=table_name, con=engine, if_exists='replace', index=False)

print(f"Data inserted successfully to {table_name} table")
df.head()

Data inserted successfully to aggreated_user table

                       state  year  quarter    brand  count    amount
0  andaman-&-nicobar-islands  2018        1   Xiaomi   1665  0.247033
1  andaman-&-nicobar-islands  2018        1  Samsung   1445  0.214392
2  andaman-&-nicobar-islands  2018        1     Vivo    982  0.145697
3  andaman-&-nicobar-islands  2018        1     Oppo    501  0.074332
4  andaman-&-nicobar-islands  2018        1  OnePlus    332  0.049258

### 2. Map

#### 2.1 Map - insurance

In [44]:
# pulse\data\map\insurance\hover\country\india\state

# Path to dataset
path = "pulse/data/map/insurance/hover/country/india/state/"

data = []

# Loop through states
for state in os.listdir(path):
    state_path = path + state + "/"
    
    for year in os.listdir(state_path):
        year_path = state_path + year + "/"
        
        for file in os.listdir(year_path):
            file_path = year_path + file
            
            with open(file_path, 'r') as f:
                d = json.load(f)
                
                if d["data"] and "hoverDataList" in d["data"]:
                    for  item in d["data"]["hoverDataList"]:
                        name=item["name"]
                        count=item["metric"][0]["count"]
                        amount=item["metric"][0]["amount"]                        
                        
                        data.append({
                            "state":state,
                            "year": int(year),
                            "quarter":int(file.strip('.json')),
                            "distric":name,
                            "insurance_count":count,
                            "insurance_amount":amount
                        })

df = pd.DataFrame(data)
# Storing data to csv file
df.to_csv(csv_filepath+"map_insurance.csv",index=False)

# Inserting Data into sql for analysing
table_name = 'map_insurance'
df.to_sql(name=table_name, con=engine, if_exists='replace', index=False)

print(f"Data inserted successfully to {table_name} table")
df.head()

Data inserted successfully to map_insurance table

,state,year,quarter,distric,insurance_count,insurance_amount
0,andaman-&-nicobar-islands,2020,2,south andaman district,3,795.0
1,andaman-&-nicobar-islands,2020,2,nicobars district,3,565.0
2,andaman-&-nicobar-islands,2020,3,north and middle andaman district,1,281.0
3,andaman-&-nicobar-islands,2020,3,south andaman district,35,13651.0
4,andaman-&-nicobar-islands,2020,3,nicobars district,5,1448.0

#### 2.2 Map-transaction

In [45]:

# Path to dataset
path = "pulse/data/map/transaction/hover/country/india/state/"

data = []

# Loop through states
for state in os.listdir(path):
    state_path = path + state + "/"
    
    for year in os.listdir(state_path):
        year_path = state_path + year + "/"
        
        for file in os.listdir(year_path):
            file_path = year_path + file
            
            with open(file_path, 'r') as f:
                d = json.load(f)
                
                if d["data"] and "hoverDataList" in d["data"]:    
                    for i in d['data']['hoverDataList']:
                        name = i['name']
                        count=i["metric"][0]["count"]
                        amount=i["metric"][0]["amount"]
                    
                        data.append({
                            "state": state,
                            "year": int(year),
                            "quarter": int(file.strip('.json')),
                            "district": name,
                            "count": count,
                            "amount": amount
                        })

df = pd.DataFrame(data)
# Storing the data into csv file
df.to_csv(csv_filepath+"map_transactions.csv",index=False)     

# Inserting Data into sql for analysing
table_name = 'map_transactions'
df.to_sql(name=table_name, con=engine, if_exists='replace', index=False)

print(f"Data inserted successfully to {table_name} table")
df.head()

Data inserted successfully to map_transactions table

,state,year,quarter,district,count,amount
0,andaman-&-nicobar-islands,2018,1,north and middle andaman district,442,9.316631e+05
1,andaman-&-nicobar-islands,2018,1,south andaman district,5688,1.256025e+07
2,andaman-&-nicobar-islands,2018,1,nicobars district,528,1.139849e+06
3,andaman-&-nicobar-islands,2018,2,north and middle andaman district,825,1.317863e+06
4,andaman-&-nicobar-islands,2018,2,south andaman district,9395,2.394824e+07

#### 2.3 Map - user

In [46]:

# Path to dataset
path = "pulse/data/map/user/hover/country/india/state/"

data = []

# Loop through states
for state in os.listdir(path):
    state_path = path + state + "/"
    
    for year in os.listdir(state_path):
        year_path = state_path + year + "/"
        
        for file in os.listdir(year_path):
            file_path = year_path + file
            
            with open(file_path, 'r') as f:
                d = json.load(f)

                hover_data = d.get("data",{}).get("hoverData",{})
            
                for district_name,metrics in hover_data.items():
                    registered_users = metrics.get("registeredUsers",0)
                    app_opens = metrics.get("appOpens",0)
                    
                    data.append({
                        "state": state,
                        "year": int(year),
                        "quarter": int(file.strip('.json')),
                        "district":district_name.title(),
                        "registered_users":registered_users,
                        "app_opens":app_opens
                    })

df = pd.DataFrame(data)
# Storing data into csv file
df.to_csv(csv_filepath+"map_user.csv",index=False)

# Inserting Data into sql for analysing
table_name = 'map_user'
df.to_sql(name=table_name, con=engine, if_exists='replace', index=False)

print(f"Data inserted successfully to {table_name} table")
df.head()

Data inserted successfully to map_user table

,state,year,quarter,district,registered_users,app_opens
0,andaman-&-nicobar-islands,2018,1,North And Middle Andaman District,632,0
1,andaman-&-nicobar-islands,2018,1,South Andaman District,5846,0
2,andaman-&-nicobar-islands,2018,1,Nicobars District,262,0
3,andaman-&-nicobar-islands,2018,2,North And Middle Andaman District,911,0
4,andaman-&-nicobar-islands,2018,2,South Andaman District,8143,0

### 3. Top

#### 3.1 Top - insurance

In [47]:
# Path to dataset
path = "pulse/data/top/insurance/country/india/state/"

districts = []
pincodes = []

# Loop through states
for state in os.listdir(path):
    state_path = path + state + "/"
    
    for year in os.listdir(state_path):
        year_path = state_path + year + "/"
        
        for file in os.listdir(year_path):
            file_path = year_path + file
            
            with open(file_path, 'r') as f:
                data = json.load(f)
                
                if data.get("data"):
                    # Adding districts data
                    for d in data["data"]["districts"]:
                        entity_name_district=d["entityName"]
                        count_districts=d["metric"]["count"]
                        amount_district=d["metric"]["amount"]
                        
                        districts.append({
                        "state": state,
                        "year": int(year),
                        "quater": int(file.strip('.json')),
                        "district_entity_name":entity_name_district,
                        "district_count":count_districts,
                        "district_amount":amount_district})        
                
                    # Adding pincodes data 
                    for p in data["data"]["pincodes"]:
                        entity_name_pincodes=p["entityName"]   
                        count_pincode=p["metric"]["count"]
                        amount_pincode=p["metric"]["amount"]
                    
                        pincodes.append({
                        "state": state,
                        "year": int(year),
                        "quater": int(file.strip('.json')),
                        "pincode_entity_name":entity_name_pincodes,
                        "pincode_count":count_pincode,
                        "pincode_amount":amount_pincode})              

top_insurance_dist_df = pd.DataFrame(districts)
top_insurance_pincode_df = pd.DataFrame(pincodes)

# Store the data into csv file
top_insurance_dist_df.to_csv(csv_filepath+"top_insurance_districs.csv",index=False)

# Inserting Data into sql for analysing
table_name = 'top_insurance_districs'
top_insurance_dist_df.to_sql(name=table_name, con=engine, if_exists='replace', index=False)

print(f"Data inserted successfully to {table_name} table")

top_insurance_pincode_df.to_csv(csv_filepath+"top_insurance_pincodes.csv",index=False)

# Inserting Data into sql for analysing
table_name = 'top_insurance_pincodes'
top_insurance_pincode_df.to_sql(name=table_name, con=engine, if_exists='replace', index=False)

print(f"Data inserted successfully to {table_name} table")

Data inserted successfully to top_insurance_districs table
Data inserted successfully to top_insurance_pincodes table

#### 3.2 Top-Transactions

In [ ]:
# Path to dataset
path = "pulse/data/top/transaction/country/india/state/"

districts = []
pincodes = []

# Loop through states
for state in os.listdir(path):
    state_path = path + state + "/"
    
    for year in os.listdir(state_path):
        year_path = state_path + year + "/"
        
        for file in os.listdir(year_path):
            file_path = year_path + file
            
            with open(file_path, 'r') as f:
                data = json.load(f)
                
                if data.get("data"):
                    # Adding districts data
                    for d in data["data"]["districts"]:
                        entity_name_district=d["entityName"]
                        count_districts=d["metric"]["count"]
                        amount_district=d["metric"]["amount"]
                        
                        districts.append({
                        "state": state,
                        "year": int(year),
                        "quater": int(file.strip('.json')),
                        "district_entity_name":entity_name_district,
                        "district_count":count_districts,
                        "district_amount":amount_district})        
                
                    # Adding pincodes data 
                    for p in data["data"]["pincodes"]:
                        entity_name_pincodes=p["entityName"]   
                        count_pincode=p["metric"]["count"]
                        amount_pincode=p["metric"]["amount"]
                    
                        pincodes.append({
                        "state": state,
                        "year": int(year),
                        "quater": int(file.strip('.json')),
                        "pincode_entity_name":str(entity_name_pincodes),
                        "pincode_count":count_pincode,
                        "pincode_amount":amount_pincode})              

##########################
#  Districts data
########################## 

top_transaction_dist_df = pd.DataFrame(districts)
top_transaction_dist_df.to_csv(csv_filepath+"top_transaction_districs.csv",index=False)

# Inserting Data into sql for analysing
table_name = 'top_transaction_districs'
top_transaction_dist_df.to_sql(name=table_name, con=engine, if_exists='replace', index=False)

print(f"Data inserted successfully to {table_name} table")

##########################
#  Pincodes data
########################## 

top_transaction_pincode_df = pd.DataFrame(pincodes)
top_transaction_pincode_df.to_csv(csv_filepath+"top_transaction_pincodes.csv",index=False)

# Inserting Data into sql for analysing
table_name = 'top_transaction_pincodes'
top_transaction_pincode_df.to_sql(name=table_name, con=engine, if_exists='replace', index=False)

print(f"Data inserted successfully to {table_name} table")

Data inserted successfully to top_transaction_districs table
Data inserted successfully to top_transaction_pincodes table

#### 3.3 Top - User

In [49]:
# Path to dataset
path = "pulse/data/top/user/country/india/state/"

districts = []
pincodes = []

# Loop through states
for state in os.listdir(path):
    state_path = path + state + "/"
    
    for year in os.listdir(state_path):
        year_path = state_path + year + "/"
        
        for file in os.listdir(year_path):
            file_path = year_path + file
            
            with open(file_path, 'r') as f:
                data = json.load(f)
                
                if data.get("data"):
                    # Adding districts data
                    for d in data["data"]["districts"]:
                        district=d["name"]
                        reg_users=d["registeredUsers"]

                        districts.append({
                        "state": state,
                        "year": int(year),
                        "quater": int(file.strip('.json')),
                        "district_name":district,
                        "registeredUsers":reg_users})        
                
                    # Adding pincodes data 
                    for p in data["data"]["pincodes"]:
                        pincode=p["name"]   
                        reg_users=p["registeredUsers"]
                    
                        pincodes.append({
                        "state": state,
                        "year": int(year),
                        "quater": int(file.strip('.json')),
                        "pincode":pincode,
                        "registeredUsers":reg_users})              


##########################
#  Districts data
##########################

top_user_dist_df = pd.DataFrame(districts)
top_user_dist_df.to_csv(csv_filepath+"top_user_districs.csv",index=False)

# Inserting Data into sql for analysing
table_name = 'top_user_districs'
top_user_dist_df.to_sql(name=table_name, con=engine, if_exists='replace', index=False)

print(f"Data inserted successfully to {table_name} table")

##########################
#  Pincodes data
##########################

top_user_pincode_df = pd.DataFrame(pincodes)
top_user_pincode_df.to_csv(csv_filepath+"top_user_pincodes.csv",index=False)

# Inserting Data into sql for analysing
table_name = 'top_user_pincodes'
top_user_pincode_df.to_sql(name=table_name, con=engine, if_exists='replace', index=False)

print(f"Data inserted successfully to {table_name} table")

Data inserted successfully to top_user_districs table
Data inserted successfully to top_user_pincodes table

In [50]:
engine.dispose()

In [ ]:
query=f"""select * from aggreated_transaction
where year=2023 and quarter=1 and state = 'telangana'"""
ai=pd.read_sql(query,con=engine)
ai.head(10)

Empty DataFrame
Columns: [state, year, quarter, brand, count, amount]
Index: []

In [16]:
query=f"""select transaction_type, sum(amount) as total from aggreated_transaction where year=2024 and quarter=4 group by transaction_type order by total desc
"""
ai=pd.read_sql(query,con=engine)
ai.head(10)

           transaction_type         total
0     Peer-to-peer payments  2.663387e+13
1         Merchant payments  8.081430e+12
2  Recharge & bill payments  1.255973e+12
3        Financial Services  1.816233e+10
4                    Others  9.369386e+09

In [26]:
query=f"""select * from aggreated_user where year=2024 and quarter=1
"""
ai=pd.read_sql(query,con=engine)
ai.head(10)

Empty DataFrame
Columns: [state, year, quarter, brand, count, amount]
Index: []